on: [push]

jobs:
  kustomize:
    runs-on: ubuntu-latest
    name: Kustomize
    steps:
    - name: Print kustomize version
      uses: geniusmonkey/actions/gcloud/kustomize@master
      with:
        args: version
  


